### ISSUE TITLE
Support for local api spec

### ISSUE THREAD

**Issue by hardbyte** [unaguil/sphinx-swagger#12]
`requests` appears to be used to load the swagger document during sphinx build - are local files supported (e.g. from the default `_static/` directory that sphinx uses)?

**Comment by mosen** [comment]
@hardbyte I came across this limitation just today which unfortunately causes me an issue since the vendor is supplying the swagger schema inside a HTML document. yeah.

Making a PR for local schema feature.

EDIT: unaguil did add support for file:// URI's but i'd like to keep everything in `_static`.
